### ISSUE TITLE
qtmultimedia5-dev

### ISSUE THREAD

**Issue by Haotian-Shi-cyber** [berndporr/qtSinePlayer#1]
"Could not find a package configuration file provided by "Qt5Multimedia" ,Qt5MultimediaConfig.cmake and qt5multimedia-config.cmake "

in my case, it is caused by not installing qtmultimedia5-dev, instead of libqt5multimedia5-plugins, haven't look at difference though.

**Comment by berndporr** [comment]
The plugins are separate to the development files. They provide support for different audio formats which are loaded at runtime.
I've added a section which packages need to be installed.
Thanks!
